apiVersion: v1
kind: ConfigMap
metadata:
  name: arash-db-config
  name: db-config
data:
  db-name: guestbook
  db-host: arash-postgres
  redis-host: arash-redis
  db-host: postgres
  redis-host: redis
  redis-port: "6379"
