apiVersion: v1
kind: Secret
metadata:
  name: arash-db-password
  name: db-password
type: Opaque
data:
  username: Z3Vlc3Rib29r
  password: cGFzc3dvcmQxMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: arash-redis-password
  name: redis-password
type: Opaque
data:
  password: cGFzc3dvcmQ=
